name: deltakit-conda
channels:
- conda-forge
- nodefaults
dependencies:
- pandoc >=3.7.0.2,<4
- python >=3.10
- actionlint >=1.7
- pixi-pycharm >=0.0.8,<0.0.9
- pip
- pip:
  - -e ./deltakit-core/
  - -e ./deltakit-circuit/
  - -e ./deltakit-decode/
  - -e ./deltakit-explorer/
  - -e ./[dev]
