# Linting configuration for deltakit_circuit.
#
# General and format configurations are repository-wide for the moment.
extend = "../ruff.toml"
include = ["src/deltakit_circuit/**/*.py", "tests/**/*.py"]

[lint]
ignore = []

# Specific per-file ignores
[lint.per-file-ignores]
# Most of the gates are named in SCREAMING_SNAKE_CASE and that is expected.
"src/deltakit_circuit/gates/*.py" = ["N801"]
# We do not want to touch any module outside of deltakit-circuit for the moment,
# and renaming the exception in the following file would do that so ignoring
# for the moment.
"src/deltakit_circuit/_parse_stim.py" = ["N818"]
# For the moment, dynamic __all__ generation raises a lot of issues with
# F401 enabled, so ignore it where it happens, in __init__.py files.
"**/__init__.py" = ["F401"]

# Test-specific ignores.
"tests/**/*.py" = [    
    # Some tests have long function names which exceeds the line length limit in order
    # to be descriptive. The names might also not respect the camel case requirement to
    # include gate names in the function name. That is fine, so ignoring the respective
    # errors.
    "E501", 
    "N802",
    # Magic constants in tests does not seem like an issue here.
    "PLR2004",
    # ruff reports "useless attribute access" on some code but the attribute access is
    # not really useless, as the goal is to call it and see if it raises an exception,
    # so this check is also ignored. 
    "B018"
]
# One test checking for invalid parameters is basically catching on Exception. That is
# needed because the exception raised in each cases may be different, and Exception is
# the only common parent class of all of them.
"tests/test_noise_channels/test_pauli_noise.py" = ["B017"]
